#!/bin/bash

###############################################################################
# taskopen - file based notes with taskwarrior
#
# Copyright 2010-2011, Johannes Schlatow.
# All rights reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the
#
#     Free Software Foundation, Inc.,
#     51 Franklin Street, Fifth Floor,
#     Boston, MA
#     02110-1301
#     USA
#
###############################################################################

BROWSER=firefox
EDITOR=vim
TASKBIN=task

if [[ $OSTYPE =~ .*darwin.* ]] #OSX
then
   XDG=open
else 
   XDG=xdg-open
fi

FILEREGEX="/^(\/|www|http|\.|~|Message-ID:|message:)/"

if [ $# != 1 ]; then
	echo "Usage: $0 <id|filter>"
	exit 1
fi

isdigit ()
{
	[ $# -eq 1 ] || return 1

	case $1 in
		*[!0-9]*|"") return 1;;
		*) return 0;;
	esac
}

if ! isdigit "$1"; then
	# argument is a filter
	TASKCOUNT=`$TASKBIN count status.isnt:deleted status.isnt:completed $1`
	if [ $TASKCOUNT -gt 1 ]; then
		# print task list
		$TASKBIN rc.verbose=off rc.report.list.annotations=none rc.report.list.filter="status.isnt:deleted status.isnt:completed" list $1
	fi

	# remark: 'ids' command needs taskwarrior 2.0 or above
	ID=`$TASKBIN ids status.isnt:deleted status.isnt:completed $1`
else
	ID="$1"
fi

#read annotations from task info output
annotations=`$TASKBIN rc._forcecolor=no rc.defaultwidth=0 $ID | gawk '$1 ~ /^[[:digit:]]/ && $NF ~ '$FILEREGEX' {print $NF}'`
anncount=`$TASKBIN rc._forcecolor=no rc.defaultwidth=0 $ID | gawk '$1 ~ /^[[:digit:]]/ && $NF ~ '$FILEREGEX' { n++ } END { print n }'`

if [ -z "$anncount" ]; then
	echo "No annotation found."
	exit 1
else
	echo "$anncount annotation(s) found."
fi

#choose an annotiation/file to open
if [ $anncount -gt 1 ]; then
	echo
	echo "Please select an annotation:"
	i=0;
	for ann in $annotations
	do
		i=$((i+1))
		files[i]=$ann
		echo "    $i) $ann"
	done

	#read digit from stdin
	read -p "Type number: " choice

	#check it
	if [ $choice -le $i -a $choice -ge 1 ]; then
		file=${files[$choice]}
	else
		echo "$choice is not a valid number"
		exit 1
	fi
else
	file=$annotations
fi

#open $file with an appropriate program
if [[ $file =~ ^http|^www ]]; then
	$BROWSER $file &
elif [[ $file =~ Message-ID ]]; then
	echo $file | muttjump && clear
elif [[ `file $file | awk '{print $NF}'` =~ text ]]; then
	$SHELL -c "$EDITOR $file"
else 
	$XDG $file &
fi

exit 0
