#!/bin/bash

BROWSER='firefox'
EDITOR='vim'
TASKBIN='/usr/bin/task'

# If you sync tasks FOLDER should be a location that syncs and is available to
# other computers, i.e. /users/dropbox/tasknotes
# FOLDER to store notes in, must already exist!
FOLDER="~/Notes/vimnotes/"

# Preferred extension for tasknotes
EXT=""

# Path to notes file. UUID will be replaced with the actual uuid of
# the task. If NOTES_CMD 
# Default is: ${FOLDER}UUID$EXT
#NOTES_FILE="~/Notes/vimnotes/UUID"

# Command that opens notes. UUID will be replaced with the actual uuid of 
# the task.
# Default is: $EDITOR $NOTES_FILE
NOTES_CMD="vim -c \":Note UUID\""

# Specify the default sorting.
# Default is taskwarrior's default sorting
#SORT="urgency-,label,annot"

# Apply a default taskwarrior filter in order to exclude certain tasks.
# Default is: status.is:pending
#EXCLUDE=

# Default command for '-S'
# Default is: ls -la
#SHOW_CMD="ls -la"

# Regular expression that referes to the NOTES_FILE.
# Default is: ^Notes
#NOTES_REGEX="^Notes" 

# Regular expression that identifies annotations openable by BROWSER.
# Default is: www|http
#BROWSER_REGEX="www|http"

# Regular expression that identifies file paths in annotations. Will be opened by EDITOR or
# xdg-open.
# Default is: \.|\/|~
#FILE_REGEX="\.|\/|~"

# Custom regular expression that specifies annotations passed to CUSTOM1_CMD, e.g:
#CUSTOM1_REGEX="Message-[Ii][Dd]:|message:"
#CUSTOM1_CMD="muttjumpwrapper"

# Custom regular expression that specifies annotations passed to CUSTOM2_CMD.
#CUSTOM2_REGEX=""
#CUSTOM2_CMD=""
