#!/bin/bash

#BROWSER='xdg-open'
#EDITOR='vim'
TASKBIN='/usr/bin/task'

# If you sync tasks FOLDER should be a location that syncs and is available to
# other computers, i.e. /users/dropbox/tasknotes
# FOLDER to store notes in, must already exist!
FOLDER="~/tasknotes/"

# Preferred extension for tasknotes
EXT=".txt"

# Message that gets annotated to the task to indicate that notes exist
NOTEMSG="Notes"

# Path to notes file. UUID will be replaced with the actual uuid of
# the task. If NOTES_CMD 
# Default is: ${FOLDER}UUID$EXT
#NOTES_FILE="~/tasknotes/UUID.txt"

# Command that opens notes. UUID will be replaced with the actual uuid of 
# the task.
# Default is: $EDITOR $NOTES_FILE
#NOTES_CMD="vim ~/tasknotes/UUID.txt"

# Specify the default sorting.
# Default is taskwarrior's default sorting
#SORT="urgency-,label,annot"

# Apply a default taskwarrior filter in order to exclude certain tasks.
# Default is: status.is:pending
#EXCLUDE=
