#!/bin/bash
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, rename this file to "post-commit".

REV=$(git rev-list master | wc -l)
HASH=$(git log -1 --pretty=%h)
VER=$(git describe --tags)

LAST_MSG=$(git log -1 --pretty=%s)
if [[ $LAST_MSG =~ ^Auto-commit ]]; then
    exit;
fi

# save changes
git diff taskopen.pl > taskopen.pl.orig
patch -p1 -R < taskopen.pl.orig

sed "s/VERSION=.*;/VERSION=\"$VER\";/" -i taskopen.pl
sed "s/REVNUM=.*;/REVNUM=\"$REV\";/" -i taskopen.pl
sed "s/REVHASH=.*;/REVHASH=\"$HASH\";/" -i taskopen.pl

git add taskopen.pl
git commit -m "Auto-commit (bumped revision)"

patch -p1 < taskopen.pl.orig
rm taskopen.pl.orig
